# First Analysis of the datasets

## Import and explore data

In [1]:
import pandas as pd

In [2]:
url = 'https://drive.google.com/file/d/1qNU3MiUPHp-ECb_0pPI9NKLvIgG9xFWN/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
quality_life_df = pd.read_csv(path)


url = 'https://drive.google.com/file/d/1sxuk1687yDI1ZJZSGsS_5NWTN75p3pWr/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
green_space_df = pd.read_csv(path)

In [3]:
pd.set_option("display.float_format", lambda x: "%.2f" % x)
pd.set_option("display.max_rows", 1000)

In [4]:
quality_life_df.head(10)

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,indic_ur,Urban audit indicator,unit,Unit of measure,cities,Geopolitical entity (declaring),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT001C,Wien (greater city),2009,NaN,43.70,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT001C,Wien (greater city),2012,NaN,49.00,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT001C,Wien (greater city),2015,NaN,56.00,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT001C,Wien (greater city),2019,NaN,58.40,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT001C,Wien (greater city),2023,NaN,51.90,NaN,NaN,NaN,NaN,NaN
5,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT002C,Graz,2009,NaN,29.10,NaN,NaN,NaN,NaN,NaN
6,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT002C,Graz,2012,NaN,36.00,NaN,NaN,NaN,NaN,NaN
7,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT002C,Graz,2015,NaN,41.00,NaN,NaN,NaN,NaN,NaN
8,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT002C,Graz,2019,NaN,38.30,NaN,NaN,NaN,NaN,NaN
9,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT002C,Graz,2023,NaN,35.60,NaN,NaN,NaN,NaN,NaN

In [5]:
quality_life_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15920 entries, 0 to 15919
Data columns (total 19 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   STRUCTURE                               15920 non-null  str
 1   STRUCTURE_ID                            15920 non-null  str
 2   STRUCTURE_NAME                          15920 non-null  str
 3   freq                                    15920 non-null  str
 4   Time frequency                          15920 non-null  str
 5   indic_ur                                15920 non-null  str
 6   Urban audit indicator                   15920 non-null  str
 7   unit                                    15920 non-null  str
 8   Unit of measure                         15920 non-null  str
 9   cities                                  15920 non-null  str
 10  Geopolitical entity (declaring)         15920 non-null  str
 11  TIME_PERIOD                             15920 non-null  int64
 12  Time                                    0 non-null      float64
 13  OBS_VALUE                               15817 non-null  float64
 14  Observation value                       0 non-null      float64
 15  OBS_FLAG                                328 non-null    str
 16  Observation status (Flag) V2 structure  328 non-null    str
 17  CONF_STATUS                             0 non-null      float64
 18  Confidentiality status (flag)           0 non-null      float64
dtypes: float64(5), int64(1), str(13)
memory usage: 4.8 MB

In [6]:
quality_life_df.shape

(15920, 19)

For the quality of life DataFrame:
The name of the survey is in the column  Urban audit indicator   

=> Important columns:  Urban audit indicator, Geopolitical entity (declaring), TIME_PERIOD, OBS_VALUE
It might be necessary to adjust and rename some of the cities in this DataFrame to fit with the others.

The columns Time, Observation value, CONF_STATUS, Confidentially status (flag) are Just NULLs.
While the colums OBS_Value, OBS_FLAG, Observation status (Flag) V2 structure are missing some or a lot of values.

In [7]:
green_space_df.head(10)

,City name:text,Total green infrastructure:number,Urban green space:number,Urban tree cover:number
0,EEA-38 cities average,42,3,30
1,Capital cities average,41,7,29
2,Valletta,17,2,7
3,Athens,17,15,11
4,Nicosia,21,2,4
5,Pristina,22,4,10
6,Skopje,24,6,15
7,Paris,26,11,20
8,Bucharest,26,6,22
9,Reykjavík,27,0,5

In [8]:
green_space_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 4 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   City name:text                     39 non-null     str
 1   Total green infrastructure:number  39 non-null     int64
 2   Urban green space:number           39 non-null     int64
 3   Urban tree cover:number            39 non-null     int64
dtypes: int64(3), str(1)
memory usage: 1.6 KB

In [9]:
green_space_df.shape

(39, 4)

37 Cities, the names are in english so the names need to be adjusted to fit.
One row for the average.
Column names should be adjusted for potential mastersheet.

## Check for overlapping cities

In [10]:
green_space_df["City name:text"].unique()

<ArrowStringArray>
[ 'EEA-38 cities average', 'Capital cities average',               'Valletta',
                 'Athens',                'Nicosia',               'Pristina',
                 'Skopje',                  'Paris',              'Bucharest',
              'Reykjavík',             'Copenhagen',               'Belgrade',
              'Amsterdam',                 'Tirana',              'Podgorica',
                   'Rome',                 'Dublin',                 'Ankara',
               'Budapest',                 'Prague',             'Bratislava',
             'Luxembourg',               'Brussels',                 'Vienna',
               'Sarajevo',                  'Sofia',                   'Riga',
                 'Warsaw',              'Stockholm',                 'Lisbon',
                'Tallinn',                 'Berlin',                   'Bern',
                 'Madrid',                'Vilnius',               'Helsinki',
              'Ljubljana',                 'Zagreb',                   'Oslo']
Length: 39, dtype: str

In [11]:
quality_life_df["Geopolitical entity (declaring)"].unique()

<ArrowStringArray>
[             'Wien (greater city)',                             'Graz',
 'Bruxelles/Brussel (greater city)',         'Antwerpen (greater city)',
             'Liège (greater city)',                            'Sofia',
                           'Burgas',            'Zurich (greater city)',
            'Geneva (greater city)',          'Lefkosia (greater city)',
 ...
                           'Ankara',                          'Antalya',
                       'Diyarbakir',                         'Istanbul',
                           'London',                          'Glasgow',
                       'Manchester',                          'Cardiff',
                          'Belfast',              'Newcastle upon Tyne']
Length: 116, dtype: str

In [12]:
greater_cities = quality_life_df[quality_life_df["Geopolitical entity (declaring)"].str.contains("(greater city)", regex=False, na=False)]
print(greater_cities["Geopolitical entity (declaring)"].drop_duplicates().tolist())

['Wien (greater city)', 'Bruxelles/Brussel (greater city)', 'Antwerpen (greater city)', 'Liège (greater city)', 'Zurich (greater city)', 'Geneva (greater city)', 'Lefkosia (greater city)', 'København (greater city)', 'Athina (greater city)', 'Irakleio (greater city)', 'Madrid (greater city)', 'Barcelona (greater city)', 'Paris (greater city)', 'Lille (greater city)', 'Marseille (greater city)', 'Bordeaux (greater city)', 'Strasbourg (greater city)', 'Rennes (greater city)', 'Budapest (greater city)', 'Dublin (greater city)', 'Napoli (greater city)', 'Luxembourg (greater city)', 'Amsterdam (greater city)', 'Rotterdam (greater city)', 'Oslo (greater city)', 'Lisboa (greater city)', 'Braga (greater city)', 'Stockholm (greater city)', 'Bratislava (greater city)', 'Košice (greater city)']

## Fixing city names

In [13]:
quality_life_cl = quality_life_df.copy()

In [14]:
quality_life_cl["Geopolitical entity (declaring)"] = quality_life_df["Geopolitical entity (declaring)"].str.replace(" (greater city)", "", regex=False)
quality_life_cl["Geopolitical entity (declaring)"].unique()

<ArrowStringArray>
[               'Wien',                'Graz',   'Bruxelles/Brussel',
           'Antwerpen',               'Liège',               'Sofia',
              'Burgas',              'Zurich',              'Geneva',
            'Lefkosia',
 ...
              'Ankara',             'Antalya',          'Diyarbakir',
            'Istanbul',              'London',             'Glasgow',
          'Manchester',             'Cardiff',             'Belfast',
 'Newcastle upon Tyne']
Length: 116, dtype: str

In [15]:
# codes of cities written in their native tongue)
missing_codes = [
    "MT001C",  # Valletta
    "CY001C",  # Nicosia
    "MK001C",  # Skopje
    "RO001C",  # Bucharest
    "RS001C",  # Belgrade
    "AL001C",  # Tirana
    "ME001C",  # Podgorica
    "IT001C",  # Rome
    "LV001C",  # Riga
    "PL001C",  # Warsaw
    "PT001C",  # Lisbon
    "AT001C",  # Vienna
    "FI001C",  # Helsinki
]

# Find unique city names for these codes
missing_cities = (quality_life_cl.loc[quality_life_cl["cities"].isin(missing_codes),["cities", "Geopolitical entity (declaring)"]].drop_duplicates().sort_values("cities")
)

print(missing_cities.to_string(index=False))

cities Geopolitical entity (declaring)
AT001C                            Wien
CY001C                        Lefkosia
FI001C            Helsinki/Helsingfors
IT001C                            Roma
LV001C                            Rīga
MT001C                Greater Valletta
PL001C                        Warszawa
PT001C                          Lisboa
RO001C                       București

In [16]:
quality_life_cl

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,freq,Time frequency,indic_ur,Urban audit indicator,unit,Unit of measure,cities,Geopolitical entity (declaring),TIME_PERIOD,Time,OBS_VALUE,Observation value,OBS_FLAG,Observation status (Flag) V2 structure,CONF_STATUS,Confidentiality status (flag)
0,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT001C,Wien,2009,NaN,43.70,NaN,NaN,NaN,NaN,NaN
1,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT001C,Wien,2012,NaN,49.00,NaN,NaN,NaN,NaN,NaN
2,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT001C,Wien,2015,NaN,56.00,NaN,NaN,NaN,NaN,NaN
3,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT001C,Wien,2019,NaN,58.40,NaN,NaN,NaN,NaN,NaN
4,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS1052V,Green spaces such as public parcs or gardens: ...,PC,Percentage,AT001C,Wien,2023,NaN,51.90,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15915,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS9292V,You are satisfied to live in this city: agree,PC,Percentage,UK001C,London,2015,NaN,90.00,NaN,NaN,NaN,NaN,NaN
15916,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS9292V,You are satisfied to live in this city: agree,PC,Percentage,UK004C,Glasgow,2015,NaN,95.00,NaN,NaN,NaN,NaN,NaN
15917,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS9292V,You are satisfied to live in this city: agree,PC,Percentage,UK008C,Manchester,2015,NaN,92.00,NaN,NaN,NaN,NaN,NaN
15918,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS9292V,You are satisfied to live in this city: agree,PC,Percentage,UK009C,Cardiff,2015,NaN,97.00,NaN,NaN,NaN,NaN,NaN
15919,dataflow,ESTAT:URB_PERCEP(1.0),Perception survey results,A,Annual,PS9292V,You are satisfied to live in this city: agree,PC,Percentage,UK012C,Belfast,2015,NaN,98.00,NaN,NaN,NaN,NaN,NaN

Drop unimoprtant columns

In [17]:
columns_to_drop = [
    "STRUCTURE",
    "STRUCTURE_NAME",
    "STRUCTURE_ID",
    "freq",
    "Time frequency",
    "unit",
    "cities",
    "Unit of measure",
    "Observation status (Flag) V2 structure",
    "Observation value",
    "CONF_STATUS",
    "Confidentiality status (flag)",
    "Time",
    "CONF_STATUS",
    "OBS_FLAG"
]

quality_life_cl = quality_life_cl.drop(columns=columns_to_drop)
quality_life_cl

,indic_ur,Urban audit indicator,Geopolitical entity (declaring),TIME_PERIOD,OBS_VALUE
0,PS1052V,Green spaces such as public parcs or gardens: ...,Wien,2009,43.70
1,PS1052V,Green spaces such as public parcs or gardens: ...,Wien,2012,49.00
2,PS1052V,Green spaces such as public parcs or gardens: ...,Wien,2015,56.00
3,PS1052V,Green spaces such as public parcs or gardens: ...,Wien,2019,58.40
4,PS1052V,Green spaces such as public parcs or gardens: ...,Wien,2023,51.90
...,...,...,...,...,...
15915,PS9292V,You are satisfied to live in this city: agree,London,2015,90.00
15916,PS9292V,You are satisfied to live in this city: agree,Glasgow,2015,95.00
15917,PS9292V,You are satisfied to live in this city: agree,Manchester,2015,92.00
15918,PS9292V,You are satisfied to live in this city: agree,Cardiff,2015,97.00
15919,PS9292V,You are satisfied to live in this city: agree,Belfast,2015,98.00

Clean-up column names and adjust city names to fit green spaces table.

Urban audit indicator = survey
Geopolitical entity (declaring) = city
TIME_PERIOD = time period
OBS_VALUE = percentage


Time period to fit with the green spaces table ~2018 <=> latest quality of life survey year to fit 2019 
=> to fit with Urban Atlas' latest dataset ~2021 <=> latest quality of life survey year to fit 2023

either 2018 => less time difference or 2021 with a 2 year difference

In [18]:
# Column name adjustment
quality_life_cl = quality_life_cl.rename(columns={
    "Urban audit indicator": "survey",
    "indic_ur": "id",
    "Geopolitical entity (declaring)": "city",
    "TIME_PERIOD": "year",
    "OBS_VALUE": "percentage"
})

In [19]:
# same with the columns of the green_space_df
green_space_df = green_space_df.rename(columns={
    "City name:text": "city",
    "Total green infrastructure:number": "total_green_infrastructure",
    "Urban green space:number": "urban_green_space",
    "Urban tree cover:number": "urban_tree_cover"
})

The percentages are in integers. Changing them to float to match the life_quaity_df

In [20]:
percentage_cols = [
    "urban_green_space",
    "urban_tree_cover",
    "total_green_infrastructure"
]

green_space_df[percentage_cols] = green_space_df[percentage_cols].astype(float)

Issue between the two tables: they use different city names. The table for green spaces uses the english names, while the quality of life table uses the local names. \
For readability the english names will be used.

In [21]:
city_names_fix = {
    "Wien": "Vienna",
    "Bruxelles/Brussel": "Brussels",
    "Praha": "Prague",
    "København": "Copenhagen",
    "Athina": "Athens",
    "Lefkosia": "Nicosia",
    "Helsinki/Helsingfors": "Helsinki",
    "Roma": "Rome",
    "Rīga": "Riga",
    "Greater Valletta": "Valletta",
    "Warszawa": "Warsaw",
    "Lisboa": "Lisbon",
    "București": "Bucharest"
}

quality_life_cl["city"] = quality_life_cl["city"].replace(city_names_fix)

Only keep matching cities

In [22]:
green_space_df

,city,total_green_infrastructure,urban_green_space,urban_tree_cover
0,EEA-38 cities average,42.00,3.00,30.00
1,Capital cities average,41.00,7.00,29.00
2,Valletta,17.00,2.00,7.00
3,Athens,17.00,15.00,11.00
4,Nicosia,21.00,2.00,4.00
5,Pristina,22.00,4.00,10.00
6,Skopje,24.00,6.00,15.00
7,Paris,26.00,11.00,20.00
8,Bucharest,26.00,6.00,22.00
9,Reykjavík,27.00,0.00,5.00
10,Copenhagen,30.00,10.00,16.00
11,Belgrade,31.00,8.00,22.00
12,Amsterdam,31.00,5.00,14.00
13,Tirana,31.00,3.00,13.00
14,Podgorica,33.00,12.00,11.00
15,Rome,34.00,3.00,24.00
16,Dublin,35.00,15.00,20.00
17,Ankara,35.00,5.00,27.00
18,Budapest,36.00,7.00,26.00
19,Prague,36.00,9.00,29.00
20,Bratislava,41.00,2.00,36.00
21,Luxembourg,42.00,4.00,37.00
22,Brussels,42.00,12.00,37.00
23,Vienna,44.00,10.00,34.00
24,Sarajevo,46.00,5.00,28.00
25,Sofia,46.00,4.00,37.00
26,Riga,46.00,6.00,43.00
27,Warsaw,47.00,6.00,40.00
28,Stockholm,48.00,19.00,34.00
29,Lisbon,48.00,2.00,17.00
30,Tallinn,50.00,10.00,43.00
31,Berlin,51.00,9.00,44.00
32,Bern,53.00,4.00,53.00
33,Madrid,53.00,9.00,39.00
34,Vilnius,57.00,8.00,47.00
35,Helsinki,62.00,5.00,44.00
36,Ljubljana,67.00,1.00,50.00
37,Zagreb,74.00,2.00,46.00
38,Oslo,77.00,3.00,72.00

In [23]:
matching_cities = green_space_df["city"].unique()

quality_life_cl = quality_life_cl[quality_life_cl["city"].isin(matching_cities)]

In [24]:
quality_life_cl.info()

<class 'pandas.DataFrame'>
Index: 5389 entries, 0 to 15911
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          5389 non-null   str
 1   survey      5389 non-null   str
 2   city        5389 non-null   str
 3   year        5389 non-null   int64
 4   percentage  5389 non-null   float64
dtypes: float64(1), int64(1), str(3)
memory usage: 676.7 KB

In [25]:
quality_life_cl["id"].value_counts()

id
PS1052V    144
PS1053V    144
PS1054V    144
PS1055V    144
PS3062V    144
PS3063V    144
PS3064V    144
PS3065V    143
PS3066V    142
PS1056V    135
PS3260V    117
PS3261V    117
PS3262V    117
PS3263V    117
PS3280V    117
PS3281V    117
PS3282V    117
PS3283V    117
PS3350V    117
PS3351V    117
PS3352V    117
PS3264V    114
PS3353V    114
PS3284V    106
PS3354V    106
PS3360V     88
PS3361V     88
PS3362V     88
PS3363V     88
PS3364V     88
PS3122V     85
PS3123V     85
PS3124V     85
PS3125V     85
PS3126V     85
PS3211V     85
PS3212V     85
PS3213V     85
PS3214V     85
PS3215V     85
PS3216V     85
PS3217V     85
PS3222V     85
PS3223V     85
PS3224V     85
PS3220V     58
PS9292V     29
PS3052V     27
PS3053V     27
PS3054V     27
PS3055V     27
PS3056V     27
PS3072V     27
PS3073V     27
PS3074V     27
PS3075V     27
PS3076V     27
PS3132V     27
PS3133V     27
PS3134V     27
PS3135V     27
PS3136V     27
PS3221V     27
Name: count, dtype: int64

In [26]:
quality_life_cl[["id", "city", "year", "percentage"]].head(10)

         id      city  year  percentage
0   PS1052V    Vienna  2009       43.70
1   PS1052V    Vienna  2012       49.00
2   PS1052V    Vienna  2015       56.00
3   PS1052V    Vienna  2019       58.40
4   PS1052V    Vienna  2023       51.90
10  PS1052V  Brussels  2009       24.60
11  PS1052V  Brussels  2012       32.00
12  PS1052V  Brussels  2015       31.00
13  PS1052V  Brussels  2019       31.80
14  PS1052V  Brussels  2023       37.20

In [42]:
# manually adding country information to the DataFrame
city_to_country = {
    "Vienna": "Austria",
    "Brussels": "Belgium",
    "Sofia": "Bulgaria",
    "Nicosia": "Cyprus",
    "Prague": "Czechia",
    "Berlin": "Germany",
    "Copenhagen": "Denmark",
    "Tallinn": "Estonia",
    "Athens": "Greece",
    "Madrid": "Spain",
    "Paris": "France",
    "Zagreb": "Croatia",
    "Budapest": "Hungary",
    "Dublin": "Ireland",
    "Reykjavík": "Iceland",
    "Rome": "Italy",
    "Vilnius": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Riga": "Latvia",
    "Valletta": "Malta",
    "Amsterdam": "Netherlands",
    "Oslo": "Norway",
    "Warsaw": "Poland",
    "Lisbon": "Portugal",
    "Bucharest": "Romania",
    "Stockholm": "Sweden",
    "Ljubljana": "Slovenia",
    "Bratislava": "Slovakia",
    "Ankara": "Türkiye"
}
quality_life_cl["country"] = quality_life_cl["city"].map(city_to_country)

## Creating DataFrames for relevant and important surveys

Split the quality_life_cl into their different surveys, only keeping the most relevant and important ones.

In [28]:
# Checking the codes on the DataSets Website, using them to filter.
# Satisfaction with living in the city
city_satisfaction= quality_life_cl[quality_life_cl["id"].isin(["PS3360V", "PS3361V", "PS3362V", "PS3363V", "PS3364V"])].copy()

# Satisfaction with green spaces
green_satisfaction = quality_life_cl[quality_life_cl["id"].isin(["PS1052V", "PS1053V", "PS1054V", "PS1055V", "PS1056V" ])].copy()

# Perceived healthiness of the city
city_health = quality_life_cl[quality_life_cl["id"].isin(["PS3132V", "PS3133V", "PS3134V", "PS3135V", "PS3136V"])].copy()

# Satisfaction with air quality
air_quality = quality_life_cl[quality_life_cl["id"].isin(["PS3260V", "PS3261V", "PS3262V", "PS3263V", "PS3264V"])].copy()

In [29]:
print("City satisfaction:", city_satisfaction.shape)
print("Green satisfaction:", green_satisfaction.shape)
print("City healthiness:", city_health.shape)
print("Air quality:", air_quality.shape)

City satisfaction: (440, 6)
Green satisfaction: (711, 6)
City healthiness: (135, 6)
Air quality: (582, 6)

## Creating a master sheet

Keeping the year 2019, since it's the closest to the green space data (2018)

In [30]:
quality_life_cl = quality_life_cl[quality_life_cl["year"] == 2019].copy()

In [31]:
quality_life_cl["city"].unique()

<ArrowStringArray>
[    'Vienna',   'Brussels',      'Sofia',    'Nicosia',     'Prague',
     'Berlin', 'Copenhagen',    'Tallinn',     'Athens',     'Madrid',
      'Paris',     'Zagreb',   'Budapest',     'Dublin',  'Reykjavík',
       'Rome',    'Vilnius', 'Luxembourg',       'Riga',   'Valletta',
  'Amsterdam',       'Oslo',     'Warsaw',     'Lisbon',  'Bucharest',
  'Stockholm',  'Ljubljana', 'Bratislava',     'Ankara']
Length: 29, dtype: str

Total matching cities: 29

Keep the positive survey results for city and green space satisfaction

In [32]:
# City satisfaction: strongly agree
city_strong = quality_life_cl[quality_life_cl["id"] == "PS3360V"][["city", "year", "percentage"]].copy()

city_strong = city_strong.rename(columns={"percentage": "city_strongly_agree"})

# City satisfaction: somewhat agree
city_somewhat = quality_life_cl[quality_life_cl["id"] == "PS3361V"][["city", "year", "percentage"]].copy()

city_somewhat = city_somewhat.rename(columns={"percentage": "city_somewhat_agree"})

In [33]:
# Green spaces: very satisfied
green_very = quality_life_cl[quality_life_cl["id"] == "PS1052V"][["city", "year", "percentage"]].copy()

green_very = green_very.rename(columns={"percentage": "green_very_satisfied"})

# Green spaces: rather satisfied
green_rather = quality_life_cl[quality_life_cl["id"] == "PS1053V"][["city", "year", "percentage"]].copy()

green_rather = green_rather.rename(columns={"percentage": "green_rather_satisfied"})

merge the tables into a master sheet

In [34]:
survey_master = city_strong.merge(city_somewhat, 
                                  on=["city", "year"], 
                                  how="inner")

survey_master = survey_master.merge(green_very, 
                                    on=["city", "year"], 
                                    how="inner")

survey_master = survey_master.merge(green_rather, 
                                    on=["city", "year"], 
                                    how="inner")

survey_master

,city,year,city_strongly_agree,city_somewhat_agree,green_very_satisfied,green_rather_satisfied
0,Vienna,2019,73.90,19.80,58.40,31.10
1,Brussels,2019,37.70,49.70,31.80,52.20
2,Sofia,2019,34.20,48.20,12.70,51.00
3,Nicosia,2019,38.70,46.40,19.60,34.10
4,Prague,2019,40.30,52.00,30.50,48.10
5,Berlin,2019,55.80,34.70,37.20,49.60
6,Copenhagen,2019,77.80,20.10,50.70,39.20
7,Tallinn,2019,54.90,36.70,35.90,49.10
8,Athens,2019,15.00,49.10,6.70,22.30
9,Madrid,2019,40.80,42.80,24.70,42.60
10,Paris,2019,40.00,45.40,30.30,53.20
11,Zagreb,2019,60.50,29.20,34.30,47.00
12,Budapest,2019,42.10,43.90,18.90,50.30
13,Dublin,2019,67.30,26.40,52.50,33.90
14,Reykjavík,2019,64.80,28.70,26.50,48.70
15,Rome,2019,24.30,49.90,15.70,43.10
16,Vilnius,2019,61.90,32.10,32.50,52.40
17,Luxembourg,2019,69.90,24.50,51.10,37.30
18,Riga,2019,30.00,50.40,33.50,51.30
19,Valletta,2019,43.80,36.80,19.10,23.90
20,Amsterdam,2019,68.80,25.20,42.00,45.70
21,Oslo,2019,82.70,14.40,47.20,45.80
22,Warsaw,2019,46.90,45.30,35.50,47.80
23,Lisbon,2019,23.60,63.90,11.60,55.40
24,Bucharest,2019,31.90,48.90,19.70,41.70
25,Stockholm,2019,81.40,16.20,49.60,40.90
26,Ljubljana,2019,68.20,25.30,48.70,38.10
27,Bratislava,2019,44.80,46.70,14.10,40.40
28,Ankara,2019,63.80,26.70,43.10,33.30

In [35]:
survey_master = survey_master.merge(green_space_df,
                                    on="city",
                                    how="inner")
survey_master

,city,year,city_strongly_agree,city_somewhat_agree,green_very_satisfied,green_rather_satisfied,total_green_infrastructure,urban_green_space,urban_tree_cover
0,Vienna,2019,73.90,19.80,58.40,31.10,44.00,10.00,34.00
1,Brussels,2019,37.70,49.70,31.80,52.20,42.00,12.00,37.00
2,Sofia,2019,34.20,48.20,12.70,51.00,46.00,4.00,37.00
3,Nicosia,2019,38.70,46.40,19.60,34.10,21.00,2.00,4.00
4,Prague,2019,40.30,52.00,30.50,48.10,36.00,9.00,29.00
5,Berlin,2019,55.80,34.70,37.20,49.60,51.00,9.00,44.00
6,Copenhagen,2019,77.80,20.10,50.70,39.20,30.00,10.00,16.00
7,Tallinn,2019,54.90,36.70,35.90,49.10,50.00,10.00,43.00
8,Athens,2019,15.00,49.10,6.70,22.30,17.00,15.00,11.00
9,Madrid,2019,40.80,42.80,24.70,42.60,53.00,9.00,39.00
10,Paris,2019,40.00,45.40,30.30,53.20,26.00,11.00,20.00
11,Zagreb,2019,60.50,29.20,34.30,47.00,74.00,2.00,46.00
12,Budapest,2019,42.10,43.90,18.90,50.30,36.00,7.00,26.00
13,Dublin,2019,67.30,26.40,52.50,33.90,35.00,15.00,20.00
14,Reykjavík,2019,64.80,28.70,26.50,48.70,27.00,0.00,5.00
15,Rome,2019,24.30,49.90,15.70,43.10,34.00,3.00,24.00
16,Vilnius,2019,61.90,32.10,32.50,52.40,57.00,8.00,47.00
17,Luxembourg,2019,69.90,24.50,51.10,37.30,42.00,4.00,37.00
18,Riga,2019,30.00,50.40,33.50,51.30,46.00,6.00,43.00
19,Valletta,2019,43.80,36.80,19.10,23.90,17.00,2.00,7.00
20,Amsterdam,2019,68.80,25.20,42.00,45.70,31.00,5.00,14.00
21,Oslo,2019,82.70,14.40,47.20,45.80,77.00,3.00,72.00
22,Warsaw,2019,46.90,45.30,35.50,47.80,47.00,6.00,40.00
23,Lisbon,2019,23.60,63.90,11.60,55.40,48.00,2.00,17.00
24,Bucharest,2019,31.90,48.90,19.70,41.70,26.00,6.00,22.00
25,Stockholm,2019,81.40,16.20,49.60,40.90,48.00,19.00,34.00
26,Ljubljana,2019,68.20,25.30,48.70,38.10,67.00,1.00,50.00
27,Bratislava,2019,44.80,46.70,14.10,40.40,41.00,2.00,36.00
28,Ankara,2019,63.80,26.70,43.10,33.30,35.00,5.00,27.00

Drop year column, since it's not going to be used for the analysis

In [36]:
survey_master = survey_master.drop(columns="year")

survey_master

,city,city_strongly_agree,city_somewhat_agree,green_very_satisfied,green_rather_satisfied,total_green_infrastructure,urban_green_space,urban_tree_cover
0,Vienna,73.90,19.80,58.40,31.10,44.00,10.00,34.00
1,Brussels,37.70,49.70,31.80,52.20,42.00,12.00,37.00
2,Sofia,34.20,48.20,12.70,51.00,46.00,4.00,37.00
3,Nicosia,38.70,46.40,19.60,34.10,21.00,2.00,4.00
4,Prague,40.30,52.00,30.50,48.10,36.00,9.00,29.00
5,Berlin,55.80,34.70,37.20,49.60,51.00,9.00,44.00
6,Copenhagen,77.80,20.10,50.70,39.20,30.00,10.00,16.00
7,Tallinn,54.90,36.70,35.90,49.10,50.00,10.00,43.00
8,Athens,15.00,49.10,6.70,22.30,17.00,15.00,11.00
9,Madrid,40.80,42.80,24.70,42.60,53.00,9.00,39.00
10,Paris,40.00,45.40,30.30,53.20,26.00,11.00,20.00
11,Zagreb,60.50,29.20,34.30,47.00,74.00,2.00,46.00
12,Budapest,42.10,43.90,18.90,50.30,36.00,7.00,26.00
13,Dublin,67.30,26.40,52.50,33.90,35.00,15.00,20.00
14,Reykjavík,64.80,28.70,26.50,48.70,27.00,0.00,5.00
15,Rome,24.30,49.90,15.70,43.10,34.00,3.00,24.00
16,Vilnius,61.90,32.10,32.50,52.40,57.00,8.00,47.00
17,Luxembourg,69.90,24.50,51.10,37.30,42.00,4.00,37.00
18,Riga,30.00,50.40,33.50,51.30,46.00,6.00,43.00
19,Valletta,43.80,36.80,19.10,23.90,17.00,2.00,7.00
20,Amsterdam,68.80,25.20,42.00,45.70,31.00,5.00,14.00
21,Oslo,82.70,14.40,47.20,45.80,77.00,3.00,72.00
22,Warsaw,46.90,45.30,35.50,47.80,47.00,6.00,40.00
23,Lisbon,23.60,63.90,11.60,55.40,48.00,2.00,17.00
24,Bucharest,31.90,48.90,19.70,41.70,26.00,6.00,22.00
25,Stockholm,81.40,16.20,49.60,40.90,48.00,19.00,34.00
26,Ljubljana,68.20,25.30,48.70,38.10,67.00,1.00,50.00
27,Bratislava,44.80,46.70,14.10,40.40,41.00,2.00,36.00
28,Ankara,63.80,26.70,43.10,33.30,35.00,5.00,27.00

In [43]:
# adding countries to the master sheet
city_to_country = {
    "Vienna": "Austria",
    "Brussels": "Belgium",
    "Sofia": "Bulgaria",
    "Nicosia": "Cyprus",
    "Prague": "Czechia",
    "Berlin": "Germany",
    "Copenhagen": "Denmark",
    "Tallinn": "Estonia",
    "Athens": "Greece",
    "Madrid": "Spain",
    "Paris": "France",
    "Zagreb": "Croatia",
    "Budapest": "Hungary",
    "Dublin": "Ireland",
    "Reykjavík": "Iceland",
    "Rome": "Italy",
    "Vilnius": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Riga": "Latvia",
    "Valletta": "Malta",
    "Amsterdam": "Netherlands",
    "Oslo": "Norway",
    "Warsaw": "Poland",
    "Lisbon": "Portugal",
    "Bucharest": "Romania",
    "Stockholm": "Sweden",
    "Ljubljana": "Slovenia",
    "Bratislava": "Slovakia",
    "Ankara": "Türkiye"
}
survey_master["country"] = survey_master["city"].map(city_to_country)

In [44]:
survey_master

,city,city_strongly_agree,city_somewhat_agree,green_very_satisfied,green_rather_satisfied,total_green_infrastructure,urban_green_space,urban_tree_cover,country
0,Vienna,73.90,19.80,58.40,31.10,44.00,10.00,34.00,Austria
1,Brussels,37.70,49.70,31.80,52.20,42.00,12.00,37.00,Belgium
2,Sofia,34.20,48.20,12.70,51.00,46.00,4.00,37.00,Bulgaria
3,Nicosia,38.70,46.40,19.60,34.10,21.00,2.00,4.00,Cyprus
4,Prague,40.30,52.00,30.50,48.10,36.00,9.00,29.00,Czechia
5,Berlin,55.80,34.70,37.20,49.60,51.00,9.00,44.00,Germany
6,Copenhagen,77.80,20.10,50.70,39.20,30.00,10.00,16.00,Denmark
7,Tallinn,54.90,36.70,35.90,49.10,50.00,10.00,43.00,Estonia
8,Athens,15.00,49.10,6.70,22.30,17.00,15.00,11.00,Greece
9,Madrid,40.80,42.80,24.70,42.60,53.00,9.00,39.00,Spain
10,Paris,40.00,45.40,30.30,53.20,26.00,11.00,20.00,France
11,Zagreb,60.50,29.20,34.30,47.00,74.00,2.00,46.00,Croatia
12,Budapest,42.10,43.90,18.90,50.30,36.00,7.00,26.00,Hungary
13,Dublin,67.30,26.40,52.50,33.90,35.00,15.00,20.00,Ireland
14,Reykjavík,64.80,28.70,26.50,48.70,27.00,0.00,5.00,Iceland
15,Rome,24.30,49.90,15.70,43.10,34.00,3.00,24.00,Italy
16,Vilnius,61.90,32.10,32.50,52.40,57.00,8.00,47.00,Lithuania
17,Luxembourg,69.90,24.50,51.10,37.30,42.00,4.00,37.00,Luxembourg
18,Riga,30.00,50.40,33.50,51.30,46.00,6.00,43.00,Latvia
19,Valletta,43.80,36.80,19.10,23.90,17.00,2.00,7.00,Malta
20,Amsterdam,68.80,25.20,42.00,45.70,31.00,5.00,14.00,Netherlands
21,Oslo,82.70,14.40,47.20,45.80,77.00,3.00,72.00,Norway
22,Warsaw,46.90,45.30,35.50,47.80,47.00,6.00,40.00,Poland
23,Lisbon,23.60,63.90,11.60,55.40,48.00,2.00,17.00,Portugal
24,Bucharest,31.90,48.90,19.70,41.70,26.00,6.00,22.00,Romania
25,Stockholm,81.40,16.20,49.60,40.90,48.00,19.00,34.00,Sweden
26,Ljubljana,68.20,25.30,48.70,38.10,67.00,1.00,50.00,Slovenia
27,Bratislava,44.80,46.70,14.10,40.40,41.00,2.00,36.00,Slovakia
28,Ankara,63.80,26.70,43.10,33.30,35.00,5.00,27.00,Türkiye

In [46]:
# re-order the columns for better readability

survey_master = survey_master[["city",
                                     "country",
                                     "city_strongly_agree",
                                     "city_somewhat_agree",
                                     "green_very_satisfied",
                                     "green_rather_satisfied",
                                     "total_green_infrastructure",
                                     "urban_green_space",
                                     "urban_tree_cover"
                                     ]]

In [47]:
survey_master

,city,country,city_strongly_agree,city_somewhat_agree,green_very_satisfied,green_rather_satisfied,total_green_infrastructure,urban_green_space,urban_tree_cover
0,Vienna,Austria,73.90,19.80,58.40,31.10,44.00,10.00,34.00
1,Brussels,Belgium,37.70,49.70,31.80,52.20,42.00,12.00,37.00
2,Sofia,Bulgaria,34.20,48.20,12.70,51.00,46.00,4.00,37.00
3,Nicosia,Cyprus,38.70,46.40,19.60,34.10,21.00,2.00,4.00
4,Prague,Czechia,40.30,52.00,30.50,48.10,36.00,9.00,29.00
5,Berlin,Germany,55.80,34.70,37.20,49.60,51.00,9.00,44.00
6,Copenhagen,Denmark,77.80,20.10,50.70,39.20,30.00,10.00,16.00
7,Tallinn,Estonia,54.90,36.70,35.90,49.10,50.00,10.00,43.00
8,Athens,Greece,15.00,49.10,6.70,22.30,17.00,15.00,11.00
9,Madrid,Spain,40.80,42.80,24.70,42.60,53.00,9.00,39.00
10,Paris,France,40.00,45.40,30.30,53.20,26.00,11.00,20.00
11,Zagreb,Croatia,60.50,29.20,34.30,47.00,74.00,2.00,46.00
12,Budapest,Hungary,42.10,43.90,18.90,50.30,36.00,7.00,26.00
13,Dublin,Ireland,67.30,26.40,52.50,33.90,35.00,15.00,20.00
14,Reykjavík,Iceland,64.80,28.70,26.50,48.70,27.00,0.00,5.00
15,Rome,Italy,24.30,49.90,15.70,43.10,34.00,3.00,24.00
16,Vilnius,Lithuania,61.90,32.10,32.50,52.40,57.00,8.00,47.00
17,Luxembourg,Luxembourg,69.90,24.50,51.10,37.30,42.00,4.00,37.00
18,Riga,Latvia,30.00,50.40,33.50,51.30,46.00,6.00,43.00
19,Valletta,Malta,43.80,36.80,19.10,23.90,17.00,2.00,7.00
20,Amsterdam,Netherlands,68.80,25.20,42.00,45.70,31.00,5.00,14.00
21,Oslo,Norway,82.70,14.40,47.20,45.80,77.00,3.00,72.00
22,Warsaw,Poland,46.90,45.30,35.50,47.80,47.00,6.00,40.00
23,Lisbon,Portugal,23.60,63.90,11.60,55.40,48.00,2.00,17.00
24,Bucharest,Romania,31.90,48.90,19.70,41.70,26.00,6.00,22.00
25,Stockholm,Sweden,81.40,16.20,49.60,40.90,48.00,19.00,34.00
26,Ljubljana,Slovenia,68.20,25.30,48.70,38.10,67.00,1.00,50.00
27,Bratislava,Slovakia,44.80,46.70,14.10,40.40,41.00,2.00,36.00
28,Ankara,Türkiye,63.80,26.70,43.10,33.30,35.00,5.00,27.00

In [37]:
survey_master["city"].unique()

<ArrowStringArray>
[    'Vienna',   'Brussels',      'Sofia',    'Nicosia',     'Prague',
     'Berlin', 'Copenhagen',    'Tallinn',     'Athens',     'Madrid',
      'Paris',     'Zagreb',   'Budapest',     'Dublin',  'Reykjavík',
       'Rome',    'Vilnius', 'Luxembourg',       'Riga',   'Valletta',
  'Amsterdam',       'Oslo',     'Warsaw',     'Lisbon',  'Bucharest',
  'Stockholm',  'Ljubljana', 'Bratislava',     'Ankara']
Length: 29, dtype: str

In [38]:
survey_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   city                        29 non-null     str
 1   city_strongly_agree         29 non-null     float64
 2   city_somewhat_agree         29 non-null     float64
 3   green_very_satisfied        29 non-null     float64
 4   green_rather_satisfied      29 non-null     float64
 5   total_green_infrastructure  29 non-null     float64
 6   urban_green_space           29 non-null     float64
 7   urban_tree_cover            29 non-null     float64
dtypes: float64(7), str(1)
memory usage: 2.1 KB

## Exporting the tables

In [39]:
from pathlib import Path

In [48]:
# Output folder
output_folder = Path("data\cleaned data")
output_folder.mkdir(parents=True, exist_ok=True)

# Master sheet
survey_master.to_csv(output_folder / "survey_master.csv",index=False, encoding="utf-8-sig")


# Cleaned individual main datasets
green_space_df.to_csv(output_folder / "green_space_cleaned.csv", index=False, encoding="utf-8-sig")

quality_life_cl.to_csv(output_folder / "quality_life_cleaned.csv", index=False,  encoding="utf-8-sig")


# Individual survey dataframes
city_satisfaction.to_csv(output_folder / "city_satisfaction.csv", index=False, encoding="utf-8-sig")

green_satisfaction.to_csv(output_folder / "green_space_satisfaction.csv", index=False, encoding="utf-8-sig")

city_health.to_csv(output_folder / "city_health.csv", index=False, encoding="utf-8-sig")

air_quality.to_csv(output_folder / "air_quality_satisfaction.csv", index=False, encoding="utf-8-sig")